### ISSUE TITLE
Buttons to other resources

### ISSUE THREAD

**Issue by KaiBot3000** [beckastar/ladynerds_site#11]
We have so many things! We need all the things in one place!

Embed...
- Button to our Slack channel/place to request access
- Button to our Google group
- Button to our Google drive

**Comment by laviniaclare** [comment]
Is this issue more about stubbing out buttons, or does it include making the links lead somewhere (slack button to slack signup - which would likely overlap with the slack integrationissue, google group button to google group, drive button to drive)?

**Comment by KaiBot3000** [comment]
I literally added these issues as people spoke them to me, so I can't offer clarification. This does sounds like  it overlaps, to me.

**Comment by beckastar** [comment]
These are important and can you create separate issues for each discrete item? This is hard to act on.

**Comment by KaiBot3000** [comment]
Sounds like we've taken a different path to integrating these other resources, so I'm closing this issue :)
