### ISSUE TITLE
Make "index" url lead somewhere better

### ISSUE THREAD

**Issue by laviniaclare** [beckastar/ladynerds_site#30]
## Detailed Description

Currently if you go to the "index" (base url, or '/') it shows a relatively blank page that just says "index". This is not very welcoming.
## Context

It would be helpful for the base url to lead somewhere that looks like it's part of the website rather than a weird stub to improve the flow of the website, make it look more professional, and be slightly less confusing to first time visitors.
## Possible Implementation

The two solutions I can think of are either a) have the index url redirect to the login page or b) make it some sort of splash welcome page with a picture or something nice.

**Comment by KaiBot3000** [comment]
The "about" page is coming together as a great place for non-LNs to land.

**Comment by laviniaclare** [comment]
Sweet! That sounds perfect.

**Comment by beckastar** [comment]
Ok. I'm moving the content from "about" to "index," and changing the title of "about" to "contact"

**Comment by laviniaclare** [comment]
Woot!

**Comment by beckastar** [comment]
done!
