### ISSUE TITLE
create twitter list with all ladynerds accounts

### ISSUE THREAD

**Issue by beckastar** [beckastar/ladynerds_site#37]
we need a list with all ladynerds accounts that we can embed on the ladynerds twitter page

**Comment by laviniaclare** [comment]
Currently working on this.  Right now it basically works (shows tweets BY the people we want not just tweets ABOUT the people we want, or tweets by other people entirely), except 
1) I can’t add myself 
2) it says “a twitter list by @laviniaclare” which isn’t terrible but is kind of awkward.
3) Embedding a list that only I can edit is not very maintainable, but might be unavoidable.

**Comment by laviniaclare** [comment]
I figured out a better solution.  Now it looks like this:
![screen shot 2016-05-04 at 3 22 28 pm](https://cloud.githubusercontent.com/assets/5855689/15031251/23286dfa-120c-11e6-8335-b1a28ea59e67.png)
![screen shot 2016-05-04 at 3 22 46 pm](https://cloud.githubusercontent.com/assets/5855689/15031276/4d998646-120c-11e6-9e3c-2d76a8d7dcaa.png)
